from typing import Any, Dict
from pydantic import BaseModel


class Parameter(BaseModel):
    """
    Function parameter definition.
    """

    type: str


class FunctionDefinition(BaseModel):
    """
    Callable function schema definition.
    """

    name: str
    description: str
    parameters: Dict[str, Parameter]
    returns: Dict[str, str]


class PromptInput(BaseModel):
    """
    Input prompt model.
    """

    prompt: str


class FunctionCallOutput(BaseModel):
    """
    Output generated by the engine.
    """

    prompt: str
    name: str
    parameters: Dict[str, Any]
